# Generated by Django 4.0.1 on 2022-01-20 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telecaller', '0002_student_contact_student_email_student_enquiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='telecaller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='enquiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
