# Generated by Django 4.0.1 on 2022-01-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerhead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='total_seats',
            field=models.PositiveIntegerField(max_length=40, null=True),
        ),
    ]
