# Generated by Django 4.0.1 on 2022-01-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerhead', '0002_batch_total_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='total_seats',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
