# Generated by Django 4.0.1 on 2022-01-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerhead', '0003_alter_batch_total_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch',
            field=models.CharField(max_length=120),
        ),
    ]
