# Generated by Django 4.0.1 on 2022-01-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerhead', '0004_alter_batch_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='remaining_seats',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
